# Site settings
name: 朱乃清
location: 杭州
company: 已离职
position: 工业设计师
github: https://github.com/znq11994
facebook: 
phone: 17858795008
email: 568408060@qq.com

baseurl: "/resume.io"

permalink: /:year/:month/:day/:title/

exclude: ['README.md']

# Build settings
markdown: kramdown

